services:
  dns-updater:
    image: dns-updater:latest
    build:
      context: .
    container_name: dns-updater
    restart: always
    environment:
      MYDNS_DOMAIN: ${MYDNS_DOMAIN}
      MYDNS_USERNAME: ${MYDNS_USERNAME}
      MYDNS_PASSWORD: ${MYDNS_PASSWORD}
      WEBHOOK: ${WEBHOOK}